.test: &test
  label: 'Build app and proxy, run tests and package binaries'
  agents:
    production: "true"
    platform: "linux"
  timeout_in_minutes: 60
  env:
    DOCKER_IMAGE: 'gcr.io/opensourcecoin/radicle-upstream:0.2.1'
    SHARED_MASTER_CACHE: true
  command: '.buildkite/run.sh'
  artifact_paths:
    - "app/dist/*.AppImage"
    - "app/dist/*.snap"
    - "app/cypress/screenshots/**/*.png"

.test: &test
  label: 'Build app for macOS'
  agents:
    production: "false"
    platform: "macos"
  timeout_in_minutes: 60
  command: '.buildkite/mac-n-cheese.sh'
  artifact_paths:
    - "app/dist/*.zip"
    - "app/dist/*.dmg"
    - "app/cypress/screenshots/**/*.png"

steps:
  - branches: master
    concurrency: 1
    concurrency_group: master
    <<: *test
  - branches: "!master"
    <<: *test
