env:
  DOCKER_IMAGE: 'gcr.io/opensourcecoin/mvp:0.1.0'

steps:
  - agents:
      docker: "true"
    commands:
    - 'export HOME=/cache'
    - 'export YARN_CACHE_FOLDER=/cache'
    - 'cd app'
    - 'yarn'
    - 'yarn test'
    - 'yarn test:cypress:run'
