export const colorConfig = {
  defaultTheme: "light",
  themes: [
    {
      name: "light",
      colors: [
        { name: "primary", hex: "#ff55ff" },
        { name: "primary-level-1", hex: "#ffd4ff" },
        { name: "primary-level-2", hex: "#ff87ff" },
        { name: "primary-level-6", hex: "#663b66" },
        { name: "secondary", hex: "#5555ff" },
        { name: "secondary-level-1", hex: "#e3e3ff" },
        { name: "secondary-level-2", hex: "#bfbffc" },
        { name: "secondary-level-6", hex: "#313166" },
        { name: "tertiary", hex: "#55ffff" },
        { name: "tertiary-level-1", hex: "#d4ffff" },
        { name: "tertiary-level-2", hex: "#a0f2f2" },
        { name: "tertiary-level-6", hex: "#499494" },
        { name: "positive", hex: "#53db53" },
        { name: "positive-level-1", hex: "#e3ffe3" },
        { name: "positive-level-2", hex: "#b5ffb5" },
        { name: "positive-level-6", hex: "#569656" },
        { name: "caution", hex: "#ffc555" },
        { name: "caution-level-1", hex: "#fff6e5" },
        { name: "caution-level-2", hex: "#ffe5b2" },
        { name: "caution-level-6", hex: "#b27805" },
        { name: "negative", hex: "#ff5555" },
        { name: "negative-level-1", hex: "#ffeded" },
        { name: "negative-level-2", hex: "#ff8787" },
        { name: "negative-level-6", hex: "#803d3d" },
        { name: "background", hex: "#ffffff" },
        { name: "foreground", hex: "#28333d" },
        { name: "foreground-level-1", hex: "#f8f8f8" },
        { name: "foreground-level-2", hex: "#ebeff3" },
        { name: "foreground-level-3", hex: "#c5d1db" },
        { name: "foreground-level-4", hex: "#a9b9c7" },
        { name: "foreground-level-5", hex: "#90a0af" },
        { name: "foreground-level-6", hex: "#546474" },
      ],
    },
    {
      name: "dark",
      colors: [
        { name: "primary", hex: "#ff55ff" },
        { name: "primary-level-1", hex: "#382847" },
        { name: "primary-level-2", hex: "#62326d" },
        { name: "primary-level-6", hex: "#ffd4ff" },
        { name: "secondary", hex: "#5555ff" },
        { name: "secondary-level-1", hex: "#212847" },
        { name: "secondary-level-2", hex: "#2c326d" },
        { name: "secondary-level-6", hex: "#e3e3ff" },
        { name: "tertiary", hex: "#55ffff" },
        { name: "tertiary-level-1", hex: "#214047" },
        { name: "tertiary-level-2", hex: "#2c326d" },
        { name: "tertiary-level-6", hex: "#e3e3ff" },
        { name: "positive", hex: "#53db53" },
        { name: "positive-level-1", hex: "#21402f" },
        { name: "positive-level-2", hex: "#2c6837" },
        { name: "positive-level-6", hex: "#e3ffe3" },
        { name: "caution", hex: "#ffc555" },
        { name: "caution-level-1", hex: "#2f312d" },
        { name: "caution-level-2", hex: "#524a34" },
        { name: "caution-level-6", hex: "#ffefcf" },
        { name: "negative", hex: "#ff5555" },
        { name: "negative-level-1", hex: "#38282f" },
        { name: "negative-level-2", hex: "#623237" },
        { name: "negative-level-6", hex: "#ffd4d4" },
        { name: "background", hex: "#182129" },
        { name: "foreground", hex: "#ffffff" },
        { name: "foreground-level-1", hex: "#242e38" },
        { name: "foreground-level-2", hex: "#29343d" },
        { name: "foreground-level-3", hex: "#333e47" },
        { name: "foreground-level-4", hex: "#5e6d7a" },
        { name: "foreground-level-5", hex: "#8594a1" },
        { name: "foreground-level-6", hex: "#d3dee8" },
      ],
    },
  ],
};
