export const TREE = "TREE";
export const BLOB = "BLOB";

export const IPC_DIALOG_SHOWOPENDIALOG = "IPC_DIALOG_SHOWOPENDIALOG";
export const IPC_CLIPBOARD_WRITETEXT = "IPC_CLIPBOARD_WRITETEXT";

export const USER_REGISTRATION = "USER_REGISTRATION";
export const PROJECT_REGISTRATION = "PROJECT_REGISTRATION";
