#!/usr/bin/env bash

# A pre-push hook based on the git template. This will verify that no WIP or
# autosquash commits are present. If such a commit is present, pushing will not
# be possible.

# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" != "refs/heads/main" ]
  then
    continue
  fi

  # Check for WIP commits
  commit=$(git rev-list -n 1 --grep '^\(fixup\|squash\)!' "${remote_sha}..${local_sha}")
  if [ -n "$commit" ]
  then
    echo "Push rejected: fixup or autosquash commit detected"
    exit 1
  fi
done
